function h = H_old(l, m, lp, mp)
h = (-1)^(lp + m) * sqrt((2*lp + 1)/(2*l + 1)) * ...
    sqrt((factorial(l + lp - m + mp) / factorial(l + m) / factorial(l - m)) * ...
         (factorial(l + lp + m - mp) / factorial(lp + mp) / factorial(lp - mp)));
end