function WriteTableToFile(output_path, header, table)
        [output_stream] = fopen(output_path, 'w');
        fprintf(output_stream, header);
        fclose(output_stream);
        dlmwrite(output_path, ...
            table,...
            '-append', ...
            'precision', '%.8f',...
            'delimiter', '\t');    
end